### ISSUE TITLE
tuple parameter unpacking in image_not_ready.py

### ISSUE THREAD

**Issue by jasinner** [openshift/origin-ci-tool#179]
Using Fedora 28 and following the instructions in the README to install oct I get this error.

Loading image_not_ready.py in PyCharm also tells me there is a problem with line 87, it says:

"tuple parameter unpacking is not supported in Python 3"

```
(venv) [jshepher@localhost origin-ci-tool]$ oct bootstrap self
Traceback (most recent call last):
  File "/home/jshepher/tools/origin-ci-tool/venv/bin/oct", line 7, in <module>
    from oct.oct import oct_command
  File "/home/jshepher/tools/origin-ci-tool/venv/lib/python3.6/site-packages/oct/oct.py", line 11, in <module>
    from .cli.image_not_ready import image_not_ready
  File "/home/jshepher/tools/origin-ci-tool/venv/lib/python3.6/site-packages/oct/cli/image_not_ready.py", line 87
    images = sorted(res['Images'], key=lambda (x): datetime.strptime(x['CreationDate'], '%Y-%m-%dT%H:%M:%S.%fZ'), reverse=True)
```

**Comment by jasinner** [comment]
Noticed python 2.7 is required on readme. Not sure why my virtualenv is using python 3, will try to figure that out.
